#ifndef ASIC_RS_FFI_H
#define ASIC_RS_FFI_H

/* Generated with cbindgen:0.28.0 */

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque factory handle. Owned by the caller; free with [`asic_rs_factory_free`].
typedef struct AsicFactory AsicFactory;

// Opaque miner handle. Owned by the caller; free with [`asic_rs_miner_free`].
typedef struct AsicMiner AsicMiner;

// Library (FFI crate) version as a static C string. Do not free.
const char *asic_rs_version(void);

// Returns the last error message for this thread (borrowed; do not free).
// Valid until the next call into the library on this thread that sets an error.
const char *asic_rs_last_error(void);

// Free a string previously returned by this library.
//
// # Safety
// `s` must be null or a pointer previously returned by this library.
void asic_rs_free_string(char *s);

// Create a new empty miner factory.
struct AsicFactory *asic_rs_factory_new(void);

// Create a factory pre-loaded with hosts from a CIDR subnet (e.g. "192.168.1.0/24").
// Returns null on error; see [`asic_rs_last_error`].
//
// # Safety
// `subnet` must be a valid C string.
struct AsicFactory *asic_rs_factory_from_subnet(const char *subnet);

// Create a factory from an octet-range description (e.g. "192","168","1","1-255").
//
// # Safety
// All octet pointers must be valid C strings.
struct AsicFactory *asic_rs_factory_from_octets(const char *o1,
                                                const char *o2,
                                                const char *o3,
                                                const char *o4);

// Create a factory from a compact range string (e.g. "192.168.1.1-255").
//
// # Safety
// `range` must be a valid C string.
struct AsicFactory *asic_rs_factory_from_range(const char *range);

// Free a factory handle.
//
// # Safety
// `factory` must be null or a pointer previously returned by this library.
void asic_rs_factory_free(struct AsicFactory *factory);

// Append hosts from a CIDR subnet. Returns 0 on success, -1 on error.
//
// # Safety
// `factory` must be a live handle; `subnet` must be a valid C string.
int32_t asic_rs_factory_with_subnet(struct AsicFactory *factory, const char *subnet);

// Append hosts from a range string. Returns 0 on success, -1 on error.
//
// # Safety
// `factory` must be a live handle; `range` must be a valid C string.
int32_t asic_rs_factory_with_range(struct AsicFactory *factory, const char *range);

// Append hosts from octet ranges. Returns 0 on success, -1 on error.
//
// # Safety
// `factory` must be a live handle; octet pointers must be valid C strings.
int32_t asic_rs_factory_with_octets(struct AsicFactory *factory,
                                    const char *o1,
                                    const char *o2,
                                    const char *o3,
                                    const char *o4);

// Enable or disable the initial port connectivity check.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_port_check(struct AsicFactory *factory, bool enabled);

// Set concurrent discovery limit.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_concurrent_limit(struct AsicFactory *factory, uintptr_t limit);

// Set identification timeout in seconds.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_identification_timeout_secs(struct AsicFactory *factory, uint64_t secs);

// Set connectivity timeout in seconds.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_connectivity_timeout_secs(struct AsicFactory *factory, uint64_t secs);

// Set connectivity retries.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_connectivity_retries(struct AsicFactory *factory, uint32_t retries);

// Set nofile (RLIMIT_NOFILE) target for large scans.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_nofile_limit(struct AsicFactory *factory, uint64_t limit);

// Enable or disable automatic nofile adjustment.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_nofile_adjustment(struct AsicFactory *factory, bool enabled);

// Apply adaptive concurrency based on the current host list size.
//
// # Safety
// `factory` must be a live handle.
void asic_rs_factory_set_adaptive_concurrency(struct AsicFactory *factory);

// Number of hosts currently configured for scanning. Returns -1 on error.
//
// # Safety
// `factory` must be a live handle.
int32_t asic_rs_factory_len(const struct AsicFactory *factory);

// Whether the factory has no hosts configured.
//
// # Safety
// `factory` must be a live handle.
bool asic_rs_factory_is_empty(const struct AsicFactory *factory);

// JSON array of configured host IP strings. Free with [`asic_rs_free_string`].
//
// # Safety
// `factory` must be a live handle.
char *asic_rs_factory_hosts_json(const struct AsicFactory *factory);

// Discover and construct a miner at `ip`.
//
// Returns 0 if found (`*out_miner` set), 1 if no supported miner responded
// (`*out_miner` null), or -1 on error.
//
// # Safety
// `factory` must be a live handle, `ip` a valid C string, `out_miner` non-null.
int32_t asic_rs_factory_get_miner(struct AsicFactory *factory,
                                  const char *ip,
                                  struct AsicMiner **out_miner);

// Scan a single IP with the factory's port pre-check.
//
// Return codes match [`asic_rs_factory_get_miner`].
//
// # Safety
// `factory` must be a live handle, `ip` a valid C string, `out_miner` non-null.
int32_t asic_rs_factory_scan_miner(struct AsicFactory *factory,
                                   const char *ip,
                                   struct AsicMiner **out_miner);

// Scan all configured hosts.
//
// On success: allocates `*out_miners` as an array of `*mut AsicMiner` of length
// `*out_len`. Free each miner with [`asic_rs_miner_free`], then free the array
// with [`asic_rs_free_miner_list`].
//
// Returns 0 on success, -1 on error.
//
// # Safety
// `factory` must be a live handle; `out_miners` and `out_len` must be non-null.
int32_t asic_rs_factory_scan(struct AsicFactory *factory,
                             struct AsicMiner ***out_miners,
                             uintptr_t *out_len);

// Free an array of miner pointers returned by [`asic_rs_factory_scan`].
// Does **not** free the individual miners — call [`asic_rs_miner_free`] first.
//
// # Safety
// `list` must be null or the pointer previously returned via `out_miners`.
void asic_rs_free_miner_list(struct AsicMiner **list, uintptr_t len);

// Free a miner handle.
//
// # Safety
// `miner` must be null or a pointer previously returned by this library.
void asic_rs_miner_free(struct AsicMiner *miner);

// IP address as a newly allocated C string. Free with [`asic_rs_free_string`].
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_ip(const struct AsicMiner *miner);

// Device info as JSON. Free with [`asic_rs_free_string`].
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_device_info_json(const struct AsicMiner *miner);

// Human-readable summary: "Make Model (Firmware): IP". Free with free_string.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_summary(const struct AsicMiner *miner);

// Expected hashboards / chips / fans as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_expected_json(const struct AsicMiner *miner);

// Capability flags as JSON. Free with [`asic_rs_free_string`].
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_supports_json(const struct AsicMiner *miner);

// Set username/password credentials. Returns 0 on success, -1 on error.
//
// # Safety
// `miner` must be a live handle; username and password must be valid C strings.
int32_t asic_rs_miner_set_auth(struct AsicMiner *miner, const char *username, const char *password);

// Set a pre-issued bearer token. Returns 0 on success, -1 on error.
//
// # Safety
// `miner` must be a live handle; `token` must be a valid C string.
int32_t asic_rs_miner_set_token(struct AsicMiner *miner, const char *token);

// Full MinerData as JSON. `exclude_json` is an optional JSON array of DataField
// names to skip. Free with [`asic_rs_free_string`].
//
// # Safety
// `miner` must be a live handle; `exclude_json` may be null.
char *asic_rs_miner_get_data_json(const struct AsicMiner *miner, const char *exclude_json);

// Check for an available firmware update. JSON object or JSON null.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_check_firmware_update_json(const struct AsicMiner *miner);

// MAC address as JSON (string or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_mac_json(const struct AsicMiner *miner);

// Serial number as JSON (string or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_serial_number_json(const struct AsicMiner *miner);

// Hostname as JSON (string or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_hostname_json(const struct AsicMiner *miner);

// API version as JSON (string or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_api_version_json(const struct AsicMiner *miner);

// Firmware version as JSON (string or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_firmware_version_json(const struct AsicMiner *miner);

// Control board version as JSON (string or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_control_board_version_json(const struct AsicMiner *miner);

// Per-board telemetry as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_hashboards_json(const struct AsicMiner *miner);

// Per-board telemetry without per-chip details as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_hashboards_no_chips_json(const struct AsicMiner *miner);

// Current hashrate as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_hashrate_json(const struct AsicMiner *miner);

// Expected hashrate as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_expected_hashrate_json(const struct AsicMiner *miner);

// Chassis fans as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_fans_json(const struct AsicMiner *miner);

// PSU fans as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_psu_fans_json(const struct AsicMiner *miner);

// Fluid/ambient temperature in °C as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_fluid_temperature_json(const struct AsicMiner *miner);

// Outlet fluid temperature in °C as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_outlet_fluid_temperature_json(const struct AsicMiner *miner);

// Power draw in watts as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_wattage_json(const struct AsicMiner *miner);

// All-time best share difficulty as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_best_share_json(const struct AsicMiner *miner);

// Session best share difficulty as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_session_best_share_json(const struct AsicMiner *miner);

// Manual tuning percent as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_tuning_percent_json(const struct AsicMiner *miner);

// Tuning target as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_tuning_target_json(const struct AsicMiner *miner);

// Scaled tuning target as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_scaled_tuning_target_json(const struct AsicMiner *miner);

// Tuning capabilities as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_tuning_capabilities_json(const struct AsicMiner *miner);

// Fault-light state as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_light_flashing_json(const struct AsicMiner *miner);

// Miner messages as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_messages_json(const struct AsicMiner *miner);

// Uptime in seconds as JSON (number or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_uptime_secs_json(const struct AsicMiner *miner);

// Whether hashing is running, as JSON bool.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_is_mining_json(const struct AsicMiner *miner);

// Operating state as JSON (object or null).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_operating_state_json(const struct AsicMiner *miner);

// Runtime pool groups as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_pools_json(const struct AsicMiner *miner);

// Writable pools configuration as JSON. Null pointer on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_pools_config_json(const struct AsicMiner *miner);

// Scaling configuration as JSON. Null pointer on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_scaling_config_json(const struct AsicMiner *miner);

// Temperature configuration as JSON. Null pointer on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_temperature_config_json(const struct AsicMiner *miner);

// Tuning configuration as JSON. Null pointer on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_tuning_config_json(const struct AsicMiner *miner);

// Fan configuration as JSON. Null pointer on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_fan_config_json(const struct AsicMiner *miner);

// Timezone configuration as JSON. Null pointer on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_timezone_config_json(const struct AsicMiner *miner);

// Available presets as JSON.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_get_presets_json(const struct AsicMiner *miner);

// Apply pools configuration from JSON. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `json` must be a valid C string.
int32_t asic_rs_miner_set_pools_config_json(const struct AsicMiner *miner, const char *json);

// Apply scaling configuration from JSON. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `json` must be a valid C string.
int32_t asic_rs_miner_set_scaling_config_json(const struct AsicMiner *miner, const char *json);

// Apply temperature configuration from JSON. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `json` must be a valid C string.
int32_t asic_rs_miner_set_temperature_config_json(const struct AsicMiner *miner, const char *json);

// Apply tuning configuration from JSON. `scaling_json` may be null. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `config_json` must be a valid C string.
int32_t asic_rs_miner_set_tuning_config_json(const struct AsicMiner *miner,
                                             const char *config_json,
                                             const char *scaling_json);

// Apply fan configuration from JSON. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `json` must be a valid C string.
int32_t asic_rs_miner_set_fan_config_json(const struct AsicMiner *miner, const char *json);

// Apply timezone configuration from JSON. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `json` must be a valid C string.
int32_t asic_rs_miner_set_timezone_config_json(const struct AsicMiner *miner, const char *json);

// Set the fault light. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_set_fault_light(const struct AsicMiner *miner, bool fault);

// Set a power limit in watts. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_set_power_limit(const struct AsicMiner *miner, double watts);

// Set a manual tuning percent. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_set_tuning_percent(const struct AsicMiner *miner, uint8_t percent);

// Restart the miner. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_restart(const struct AsicMiner *miner);

// Pause mining. `at_time_secs` < 0 means immediately. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_pause(const struct AsicMiner *miner, double at_time_secs);

// Resume mining. `at_time_secs` < 0 means immediately. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_resume(const struct AsicMiner *miner, double at_time_secs);

// Re-run discovery checks. JSON bool or null on error.
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_revalidate_json(const struct AsicMiner *miner);

// Factory reset. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle.
int32_t asic_rs_miner_factory_reset(const struct AsicMiner *miner);

// Read logs as a newly allocated C string (or null on error / unsupported).
//
// # Safety
// `miner` must be a live handle.
char *asic_rs_miner_read_logs(const struct AsicMiner *miner);

// Change the miner password. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `password` must be a valid C string.
int32_t asic_rs_miner_change_password(struct AsicMiner *miner, const char *password);

// Upgrade firmware from a local file path. Returns 1/0/-1.
//
// # Safety
// `miner` must be a live handle; `path` must be a valid C string.
int32_t asic_rs_miner_upgrade_firmware(const struct AsicMiner *miner, const char *path);

#endif  /* ASIC_RS_FFI_H */
