from _typeshed import Incomplete, StrOrBytesPath
from collections.abc import AsyncIterator, Awaitable, Sequence
from datetime import timedelta
from ipaddress import IPv4Address, IPv6Address
from typing import Final, final

@final
class AutoFanConfig:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, target_temp: float, idle_speed: int |None = None) -> AutoFanConfig: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "AutoFanConfig") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "AutoFanConfig": ...
    @property
    def idle_speed(self, /) -> int |None: ...
    @property
    def mode(self, /) -> str: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "AutoFanConfig": ...
    @property
    def target_temp(self, /) -> float: ...

@final
class BoardData:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "BoardData") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "BoardData": ...
    @property
    def active(self, /) -> bool |None: ...
    @property
    def board_temperature(self, /) -> float |None: ...
    @property
    def chips(self, /) -> list[ChipData]: ...
    @property
    def expected_chips(self, /) -> int |None: ...
    @property
    def expected_hashrate(self, /) -> HashRate |None: ...
    @property
    def frequency(self, /) -> float |None: ...
    @property
    def hashrate(self, /) -> HashRate |None: ...
    @property
    def intake_temperature(self, /) -> float |None: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "BoardData": ...
    @property
    def outlet_temperature(self, /) -> float |None: ...
    @property
    def position(self, /) -> int: ...
    @property
    def serial_number(self, /) -> str |None: ...
    @property
    def tuned(self, /) -> bool |None: ...
    @property
    def voltage(self, /) -> float |None: ...
    @property
    def working_chips(self, /) -> int |None: ...

@final
class ChipData:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "ChipData") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "ChipData": ...
    @property
    def frequency(self, /) -> float |None: ...
    @property
    def hashrate(self, /) -> HashRate |None: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "ChipData": ...
    @property
    def position(self, /) -> int: ...
    @property
    def temperature(self, /) -> float |None: ...
    @property
    def tuned(self, /) -> bool |None: ...
    @property
    def voltage(self, /) -> float |None: ...
    @property
    def working(self, /) -> bool |None: ...

@final
class DeviceInfo:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "DeviceInfo") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "DeviceInfo": ...
    @property
    def algo(self, /) -> str: ...
    @property
    def firmware(self, /) -> str: ...
    @property
    def hardware(self, /) -> MinerHardware: ...
    @property
    def make(self, /) -> str: ...
    @property
    def model(self, /) -> str: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "DeviceInfo": ...

@final
class FanData:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "FanData") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "FanData": ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "FanData": ...
    @property
    def position(self, /) -> int: ...
    @property
    def rpm(self, /) -> float |None: ...

@final
class HashAlgorithm:
    Blake2S256: Final[HashAlgorithm]
    Kadena: Final[HashAlgorithm]
    SHA256: Final[HashAlgorithm]
    Scrypt: Final[HashAlgorithm]
    X11: Final[HashAlgorithm]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...

@final
class HashRate:
    def __float__(self, /) -> float: ...
    def __format__(self, /, format_spec: str) -> str: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, value: float, unit: "HashRateUnit | None" = None, algo: "HashAlgorithm | str | None" = None) -> HashRate: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "HashRate") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "HashRate": ...
    @property
    def algo(self, /) -> str: ...
    def as_unit(self, /, unit: "HashRateUnit") -> HashRate: ...
    def into_unit(self, /, unit: "HashRateUnit") -> HashRate: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "HashRate": ...
    @property
    def unit(self, /) -> HashRateUnit: ...
    @property
    def value(self, /) -> float: ...

@final
class HashRateUnit:
    EH: Final[HashRateUnit]
    ExaHash: Final[HashRateUnit]
    GH: Final[HashRateUnit]
    GigaHash: Final[HashRateUnit]
    H: Final[HashRateUnit]
    Hash: Final[HashRateUnit]
    KH: Final[HashRateUnit]
    KiloHash: Final[HashRateUnit]
    MH: Final[HashRateUnit]
    MegaHash: Final[HashRateUnit]
    PH: Final[HashRateUnit]
    PetaHash: Final[HashRateUnit]
    TH: Final[HashRateUnit]
    TeraHash: Final[HashRateUnit]
    YH: Final[HashRateUnit]
    YottaHash: Final[HashRateUnit]
    ZH: Final[HashRateUnit]
    ZettaHash: Final[HashRateUnit]
    default: Final[HashRateUnit]
    def __int__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @classmethod
    def from_str(cls, /, value: str) -> HashRateUnit: ...
    @property
    def value(self, /) -> int: ...

@final
class ManualFanConfig:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, fan_speed: int) -> ManualFanConfig: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "ManualFanConfig") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "ManualFanConfig": ...
    @property
    def fan_speed(self, /) -> int: ...
    @property
    def mode(self, /) -> str: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "ManualFanConfig": ...

@final
class Miner:
    def __repr__(self, /) -> str: ...
    @property
    def algo(self, /) -> HashAlgorithm: ...
    @property
    def expected_chips(self, /) -> int |None: ...
    @property
    def expected_fans(self, /) -> int |None: ...
    @property
    def expected_hashboards(self, /) -> int |None: ...
    @property
    def firmware(self, /) -> str: ...
    def get_api_version(self, /) -> Awaitable[str |None]: ...
    def get_control_board_version(self, /) -> Awaitable[str |None]: ...
    def get_data(self, /) -> Awaitable[MinerData]: ...
    def get_expected_hashrate(self, /) -> Awaitable[HashRate |None]: ...
    def get_fan_config(self, /) -> Awaitable[AutoFanConfig |ManualFanConfig |None]: ...
    def get_fans(self, /) -> Awaitable[list[FanData]]: ...
    def get_firmware_version(self, /) -> Awaitable[str |None]: ...
    def get_fluid_temperature(self, /) -> Awaitable[float |None]: ...
    def get_hashboards(self, /) -> Awaitable[list[BoardData]]: ...
    def get_hashrate(self, /) -> Awaitable[HashRate |None]: ...
    def get_hostname(self, /) -> Awaitable[str |None]: ...
    def get_is_mining(self, /) -> Awaitable[bool]: ...
    def get_light_flashing(self, /) -> Awaitable[bool |None]: ...
    def get_mac(self, /) -> Awaitable[str |None]: ...
    def get_messages(self, /) -> Awaitable[list[MinerMessage]]: ...
    def get_pools(self, /) -> Awaitable[list[PoolGroupData]]: ...
    def get_pools_config(self, /) -> Awaitable[list[PoolGroup] |None]: ...
    def get_psu_fans(self, /) -> Awaitable[list[FanData]]: ...
    def get_scaling_config(self, /) -> Awaitable[ScalingConfig |None]: ...
    def get_serial_number(self, /) -> Awaitable[str |None]: ...
    def get_tuning_config(self, /) -> Awaitable[TuningConfigPower |TuningConfigHashRate |TuningConfigMode |None]: ...
    def get_tuning_target(self, /) -> Awaitable[TuningTarget.Power |TuningTarget.HashRate |TuningTarget.MiningMode |None]: ...
    def get_uptime(self, /) -> Awaitable[timedelta |None]: ...
    def get_wattage(self, /) -> Awaitable[float |None]: ...
    @property
    def hardware(self, /) -> MinerHardware: ...
    @property
    def ip(self, /) -> IPv4Address |IPv6Address: ...
    @property
    def make(self, /) -> str: ...
    @property
    def model(self, /) -> str: ...
    def pause(self, /, at_time: "timedelta | float | int | None" = None) -> Awaitable[bool |None]: ...
    def restart(self, /) -> Awaitable[bool |None]: ...
    def resume(self, /, at_time: "timedelta | float | int | None" = None) -> Awaitable[bool |None]: ...
    def set_auth(self, /, username: str, password: str) -> None: ...
    def set_fan_config(self, /, config: "AutoFanConfig | ManualFanConfig") -> Awaitable[bool |None]: ...
    def set_fault_light(self, /, fault: bool) -> Awaitable[bool |None]: ...
    def set_pools_config(self, /, groups: "Sequence[PoolGroup]") -> Awaitable[bool |None]: ...
    def set_power_limit(self, /, watts: float) -> Awaitable[bool |None]: ...
    def set_scaling_config(self, /, config: "ScalingConfig") -> Awaitable[bool |None]: ...
    def set_tuning_config(self, /, config: "TuningConfigPower | TuningConfigHashRate | TuningConfigMode", scaling_config: "ScalingConfig | None" = None) -> Awaitable[bool |None]: ...
    @property
    def supports_fan_config(self, /) -> bool: ...
    @property
    def supports_pause(self, /) -> bool: ...
    @property
    def supports_pools_config(self, /) -> bool: ...
    @property
    def supports_restart(self, /) -> bool: ...
    @property
    def supports_resume(self, /) -> bool: ...
    @property
    def supports_scaling_config(self, /) -> bool: ...
    @property
    def supports_set_fault_light(self, /) -> bool: ...
    @property
    def supports_set_power_limit(self, /) -> bool: ...
    @property
    def supports_tuning_config(self, /) -> bool: ...
    @property
    def supports_upgrade_firmware(self, /) -> bool: ...
    def upgrade_firmware(self, /, path: StrOrBytesPath) -> Awaitable[bool]: ...

@final
class MinerControlBoard:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "MinerControlBoard") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "MinerControlBoard": ...
    @property
    def known(self, /) -> bool: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "MinerControlBoard": ...
    @property
    def name(self, /) -> str: ...

@final
class MinerData:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "MinerData") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "MinerData": ...
    @property
    def api_version(self, /) -> str |None: ...
    @property
    def average_temperature(self, /) -> float |None: ...
    @property
    def control_board_version(self, /) -> MinerControlBoard |None: ...
    @property
    def device_info(self, /) -> DeviceInfo: ...
    @property
    def efficiency(self, /) -> float |None: ...
    @property
    def expected_chips(self, /) -> int |None: ...
    @property
    def expected_fans(self, /) -> int |None: ...
    @property
    def expected_hashboards(self, /) -> int |None: ...
    @property
    def expected_hashrate(self, /) -> HashRate |None: ...
    @property
    def fans(self, /) -> list[FanData]: ...
    @property
    def firmware_version(self, /) -> str |None: ...
    @property
    def fluid_temperature(self, /) -> float |None: ...
    @property
    def hashboards(self, /) -> list[BoardData]: ...
    @property
    def hashrate(self, /) -> HashRate |None: ...
    @property
    def hostname(self, /) -> str |None: ...
    @property
    def ip(self, /) -> IPv4Address |IPv6Address: ...
    @property
    def is_mining(self, /) -> bool: ...
    @property
    def light_flashing(self, /) -> bool |None: ...
    @property
    def mac(self, /) -> str |None: ...
    @property
    def messages(self, /) -> list[MinerMessage]: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "MinerData": ...
    @property
    def pools(self, /) -> list[PoolGroupData]: ...
    @property
    def psu_fans(self, /) -> list[FanData]: ...
    @property
    def schema_version(self, /) -> str: ...
    @property
    def serial_number(self, /) -> str |None: ...
    @property
    def timestamp(self, /) -> int: ...
    @property
    def total_chips(self, /) -> int |None: ...
    @property
    def tuning_target(self, /) -> TuningTarget |None: ...
    @property
    def uptime(self, /) -> timedelta |None: ...
    @property
    def wattage(self, /) -> float |None: ...

@final
class MinerFactory:
    def __new__(cls, /) -> MinerFactory: ...
    @classmethod
    def from_octets(cls, /, octet1: "str | int", octet2: "str | int", octet3: "str | int", octet4: "str | int") -> "MinerFactory": ...
    @classmethod
    def from_range(cls, /, range: str) -> MinerFactory: ...
    @classmethod
    def from_subnet(cls, /, subnet: str) -> MinerFactory: ...
    def get_miner(self, /, ip: str) -> Awaitable[Miner |None]: ...
    def scan(self, /) -> Awaitable[list[Miner]]: ...
    def scan_stream(self, /) -> AsyncIterator[Miner]: ...
    def scan_stream_with_ip(self, /) -> AsyncIterator[tuple[IPv4Address |IPv6Address, Miner |None]]: ...
    def with_concurrent_limit(self, /, limit: int) -> MinerFactory: ...
    def with_connectivity_retries(self, /, retries: int) -> MinerFactory: ...
    def with_connectivity_timeout_secs(self, /, timeout_secs: int) -> MinerFactory: ...
    def with_identification_timeout_secs(self, /, timeout_secs: int) -> MinerFactory: ...
    def with_octets(self, /, octet1: "str | int", octet2: "str | int", octet3: "str | int", octet4: "str | int") -> "MinerFactory": ...
    def with_port_check(self, /, enabled: bool) -> MinerFactory: ...
    def with_range(self, /, range: str) -> MinerFactory: ...
    def with_subnet(self, /, subnet: str) -> MinerFactory: ...

@final
class MinerHardware:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "MinerHardware") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "MinerHardware": ...
    @property
    def boards(self, /) -> int |None: ...
    @property
    def chips(self, /) -> int |None: ...
    @property
    def fans(self, /) -> int |None: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "MinerHardware": ...

@final
class MinerMessage:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "MinerMessage") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "MinerMessage": ...
    @property
    def code(self, /) -> int: ...
    @property
    def message(self, /) -> str: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "MinerMessage": ...
    @property
    def severity(self, /) -> str: ...
    @property
    def timestamp(self, /) -> int: ...

@final
class MiningMode:
    High: Final[MiningMode]
    Low: Final[MiningMode]
    Normal: Final[MiningMode]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...

@final
class Pool:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, url: "str", username: str, password: str) -> Pool: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "Pool") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "Pool": ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "Pool": ...
    @property
    def password(self, /) -> str: ...
    @property
    def url(self, /) -> str: ...
    @property
    def username(self, /) -> str: ...

@final
class PoolData:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "PoolData") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "PoolData": ...
    @property
    def accepted_shares(self, /) -> int |None: ...
    @property
    def active(self, /) -> bool |None: ...
    @property
    def alive(self, /) -> bool |None: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "PoolData": ...
    @property
    def position(self, /) -> int |None: ...
    @property
    def rejected_shares(self, /) -> int |None: ...
    @property
    def url(self, /) -> str |None: ...
    @property
    def user(self, /) -> str |None: ...

@final
class PoolGroup:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, name: str, pools: Sequence[Pool], quota: int = 1) -> PoolGroup: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "PoolGroup") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "PoolGroup": ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "PoolGroup": ...
    @property
    def name(self, /) -> str: ...
    @property
    def pools(self, /) -> list[Pool]: ...
    @property
    def quota(self, /) -> int: ...

@final
class PoolGroupData:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "PoolGroupData") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "PoolGroupData": ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "PoolGroupData": ...
    @property
    def name(self, /) -> str: ...
    @property
    def pools(self, /) -> list[PoolData]: ...
    @property
    def quota(self, /) -> int: ...

@final
class ScalingConfig:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, step: int, minimum: int, shutdown: bool |None = None, shutdown_duration: float |None = None) -> ScalingConfig: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "ScalingConfig") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "ScalingConfig": ...
    @property
    def minimum(self, /) -> int: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "ScalingConfig": ...
    @property
    def shutdown(self, /) -> bool |None: ...
    @property
    def shutdown_duration(self, /) -> float |None: ...
    @property
    def step(self, /) -> int: ...

@final
class TuningConfig:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    @staticmethod
    def _pydantic_serialize(value: "TuningConfigPower | TuningConfigHashRate | TuningConfigMode") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "TuningConfigPower | TuningConfigHashRate | TuningConfigMode": ...
    @classmethod
    def hashrate(cls, /, hr: HashRate, *, algorithm: "HashAlgorithm | str | None" = None) -> TuningConfigHashRate: ...
    @classmethod
    def mode(cls, /, mode: "MiningMode | str") -> TuningConfigMode: ...
    @classmethod
    def model_dump(cls, /, obj: "TuningConfigPower | TuningConfigHashRate | TuningConfigMode", **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "TuningConfigPower | TuningConfigHashRate | TuningConfigMode": ...
    @classmethod
    def power(cls, /, watts: float, *, algorithm: "HashAlgorithm | str | None" = None) -> TuningConfigPower: ...

@final
class TuningConfigHashRate:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, target_hashrate: HashRate, algorithm: "HashAlgorithm | str | None" = None) -> TuningConfigHashRate: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "TuningConfigHashRate") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "TuningConfigHashRate": ...
    @property
    def algorithm(self, /) -> str |None: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "TuningConfigHashRate": ...
    @property
    def target_hashrate(self, /) -> HashRate: ...
    @property
    def variant(self, /) -> str: ...

@final
class TuningConfigMode:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, target_mode: "MiningMode | str") -> TuningConfigMode: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "TuningConfigMode") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "TuningConfigMode": ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "TuningConfigMode": ...
    @property
    def target_mode(self, /) -> str: ...
    @property
    def variant(self, /) -> str: ...

@final
class TuningConfigPower:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __new__(cls, /, target_watts: float, algorithm: "HashAlgorithm | str | None" = None) -> TuningConfigPower: ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "TuningConfigPower") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "TuningConfigPower": ...
    @property
    def algorithm(self, /) -> str |None: ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "TuningConfigPower": ...
    @property
    def target_watts(self, /) -> float: ...
    @property
    def variant(self, /) -> str: ...

class TuningTarget:
    @classmethod
    def __get_pydantic_core_schema__(cls, /, _source_type: "object", _handler: "object") -> "object": ...
    def __repr__(self, /) -> str: ...
    @staticmethod
    def _pydantic_serialize(value: "TuningTarget.Power | TuningTarget.HashRate | TuningTarget.MiningMode") -> "dict[str, object]": ...
    @classmethod
    def _pydantic_validate(cls, /, value: "object") -> "TuningTarget.Power | TuningTarget.HashRate | TuningTarget.MiningMode": ...
    def model_dump(self, /, **_kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_json_schema(cls, /, **kwargs: "object") -> "dict[str, object]": ...
    @classmethod
    def model_validate(cls, /, obj: "object", **_kwargs: "object") -> "TuningTarget.Power | TuningTarget.HashRate | TuningTarget.MiningMode": ...
    @final
    class HashRate(TuningTarget):
        __match_args__: Final = ("hashrate",)
        def __new__(cls, /, hashrate: HashRate) -> TuningTarget.HashRate: ...
        @property
        def hashrate(self, /) -> HashRate: ...
    @final
    class MiningMode(TuningTarget):
        __match_args__: Final = ("mode",)
        def __new__(cls, /, mode: MiningMode) -> TuningTarget.MiningMode: ...
        @property
        def mode(self, /) -> MiningMode: ...
    @final
    class Power(TuningTarget):
        __match_args__: Final = ("watts",)
        def __new__(cls, /, watts: float) -> TuningTarget.Power: ...
        @property
        def watts(self, /) -> float: ...

def __getattr__(name: str) -> Incomplete: ...
